# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hola
tagline:          'Taral Lokhande Profile'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      'An accidental Engineer</a>.'
url:              http://taralsprofile.github.io
baseurl:          /


author:
  name:           'Taral Lokhande'
  url:            https://twitter.com/mdo

paginate:         5

google_analytics: UA-100787367-2

# Custom vars
version:          2.1.0

github:   taralsprofile/jekyll-now
  #repo:           https://github.com/poole/hyde

theme: jekyll-theme-merlot
